# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('added_at', models.DateTimeField(verbose_name='Date published')),
                ('author', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('text', models.TextField(max_length=200)),
                ('added_at', models.DateTimeField(verbose_name='Date published')),
                ('rating', models.IntegerField(verbose_name='Rating')),
                ('author', models.TextField(verbose_name='Author')),
                ('likes', models.TextField(verbose_name='Likes')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa.Question'),
        ),
    ]
